### ISSUE TITLE
Ember 3.1 native getters

### ISSUE THREAD

**Issue by Subtletree** [embermap/ember-data-storefront#43]
I'll be moving to Ember 3.1 soon, are there any hiccups with using native getters across the board with storefront, since there's no proxys?

Also what are your thoughts on a e-storefront slack channel for questions such as this that don't really qualify as gh issues?

**Comment by samselikoff** [comment]
@Subtletree Slack channel might be good but we should also prioritize answering here for others benefit.

Have not used native getters yet but they should work just as they would when using Ember Data with async: false (since that's how we use Storefront). Basically Storefront just adds a few methods to Model and Store but data access is done the same way.

Believe it should all "just work" as long as you have async: false turned on.
