### ISSUE TITLE
Load related data with includes

### ISSUE THREAD

**Issue by john-griffin** [embermap/ember-data-storefront#56]
Is it possible to specify additional includes when calling `load`?

https://embermap.github.io/ember-data-storefront/docs/api/mixins/loadable-model#load

Eg `post.load('comments,comments.author');` or `post.load('comments', {include: 'author'});`

**Comment by ryanto** [comment]
Yup! Take a look at `reloadWith`, it's made for includes.

```js
post.reloadWith('comments,comments.author').then(post => {
  post.hasMany('comments').value() // <= the comments
});
```

**Comment by john-griffin** [comment]
Thanks. I had seen that but it doesn’t match up with exactly what I’m looking for. reloadWith requires reloading the base record whereas load can fetch just the associated data.

**Comment by ryanto** [comment]
I see. It sounds like you want to take the url that `.load('comments')` would normally use and append an `?include=author` onto it, so the comments load with their authors? Is that right?

If so, storefront doesn't support this and I don't think it will for the foreseeable future. The reasoning here is it's just too easy for us to get this of thing wrong and introduce a bad abstraction. I'm confident that we can't solve this with a general solution right now, so we're going to avoid it. I know that puts more burden on you as an application developer, but I don't want to introduce an API that ends up causing problems for you down the road.

If you're uncomfortable with `reloadWith` because it reloads the base record I totally understand. That's the best answer I have if you want to use storefront, but if it doesn't work then the next best answer is to dive into Ember Data.

I'd start with the JSON:API adapter and override the methods that build the `hasMany` url. I'd probably begin somewhere around here: https://www.emberjs.com/api/ember-data/3.4/classes/DS.JSONAPIAdapter/methods/urlForFindHasMany?anchor=urlForFindHasMany

**Comment by samselikoff** [comment]
@john-griffin what are you expecting `post.load('comments,comments.author')` to do? What GET request or requests would you expect to be triggered?

**Comment by beerlington** [comment]
Hey @samselikoff!

We were trying to figure out if there was a way to load just the relationships without having to reload the parent model. Basically what `ember-data-has-many-query` does, but without using that add-on in addition to storefront.

Then I saw your comment here (https://github.com/embermap/ember-data-storefront/issues/33#issuecomment-370535908) about using sync relationships, which makes sense. using `reloadWith` forces us to make an unnecessary request for the parent record since it's loaded in a parent route, but the added complexity of introducing async relationships may not be worth it just to avoid an extra request. 

The thread where you left that comment led me to believe there was a way to do it, but looking at the associated PR, that's not the case.

**Comment by john-griffin** [comment]
Thanks for the breakdown and pointers. I appreciate you not wanting to introduce bad abstractions. This is a super common case in our apps so I'd be interested to know why you don't think this can be solved generally?

Ideally `post.load('comments,comments.author');` or `post.load('comments', {include: 'author'});` would make a single request to `/posts/1/relationships/comments?include=author`.

**Comment by samselikoff** [comment]
@beerlington what's up man! Good to see you around 🍻. `reloadWith` shouldn't be an unnecessary _request_ – just extra data for the single request (since the parent data will be loaded along with the includes). Does that make sense? (Btw this is typically what we do, and in our opinion it's fine to reload the parent. I guess there are situations where the parent has tons of data and you wouldn't want it in the subsequent payload?)

@john-griffin The main thing is that Ember Data has no API for this. So my question for you is, given that this is very common for you all, how are you doing this today?

**Comment by john-griffin** [comment]
@samselikoff we are using `ember-data-has-many-query` in our other apps to get the same effect. storefront seems much more well thought out and dabbles in the same areas so I was hoping it might cover this use case.

**Comment by ryanto** [comment]
> I'd be interested to know why you don't think this can be solved generally?

Yup, absolutely. With storefront one of the goals is to delegate as much work to ED as possible. ED has years of development and escape hatches for those extra tricky situations. We want to leverage as much as that as possible.

An example of this is how we're using the [references API](https://emberjs.com/api/ember-data/3.4/classes/DS.HasManyReference) to load these relationships under the hood. References treats the relationship it backs as a single state and there's not a blessed way for us to customize the reference based off query params. I want to follow EDs lead here. Stepping outside of references and doing our own relationship fetching feels like something we'll get wrong.

Which version of data are you on? Prior to ED 3.4, there was no way to get options through references into the adapter. In 3.4 it looks like references [can now be pass options that will make it through to the adapter](https://github.com/emberjs/data/blob/v3.4.2/addon/-record-data-private/system/references/has-many.js#L289-L309). If you're on 3.4 you might want to try accessing the reference directly and see if you can get enough information over to the the adapter to build a custom query. [This test](https://github.com/emberjs/data/blob/71b3d90e3471d61dbc3a935d1638c07c895d5667/tests/integration/references/has-many-test.js#L473) might provide some color.

If you want to go down this road ping me on slack, totally happy to help!

**Comment by samselikoff** [comment]
Another way to say what @ryanto said is that Storefront is intended to "round out" Ember Data. In our opinion the way `findRecord` and `findAll` work out of the box is confusing in certain cases, which lead to the Storefront APIs `loadRecord` and `loadAll`. They don't necessarily do "more" than Ember Data does, they just slightly alter the behavior.

In the case of `model.load()`, it really is just meant to be sugar over `model.hasMany(relationship).load()`, while also being cache-aware _to the extent that Ember Data is_. And as Ryan said, Ember Data's `Reference` classes don't currently offer APIs on querying relationships (though it seems like they may soon).

I don't think there should necessarily be a problem using `ember-data-has-many-query` alongside Storefront, although I would not expect the has-many queries to respect Storefront's cache.

Feel free to report back with any more findings.

**Comment by john-griffin** [comment]
Thanks you both for the insight here. We are on 3.4 so will take look at passing options to the adapter and if not fallback to `ember-data-has-many-query`.
