### ISSUE TITLE
Idea: Allow .load() on a hasMany to avoid n+1 on already loaded collection

### ISSUE THREAD

**Issue by kalda341** [embermap/ember-data-storefront#59]

**Comment by kalda341** [comment]
This is useful in the case where you have a store.query(), and don't want to have to re-query if you have already loaded the data.

**Comment by ryanto** [comment]
N+1s sure are bad, so thanks for opening an issue!

Do you have any code samples that show the N+1, I'd love to get a better picture of what's happening.

**Comment by kalda341** [comment]
Here's a hypothetical example that illustrates the problem.
Say for example I have loaded a blog post like:
```
const post = await this.store.loadRecord('post', postId, {include: 'comments'});
```

And later on in a component I want to load the votes for these comments.
My options are: 

```
await this.store.loadRecord('post', this.post.id, {include: 'comments,comments.votes'});
```
Which is nice in terms of caching, but I'm loading data that I already have, it's not very descriptive of what I want to do, and I don't really like nested includes.

```
await this.store.query('comments', {filter: {post: this.post.id}, include: 'votes});
```
Which means I lose potential caching, both if I run this query again, and later if I call load('votes') on a comment.

Or I could do what most closely resembles what I want to do:
```
await rsvp.all(this.post.comments.map(comment => comment.load('votes')))
```
Which would be good from a caching point of view, but result in n+1;


I'm proposing something like:
```
await this.post.hasMany('comments').load('votes');
```
Which would findMany vote records if they hadn't already been loaded.

What are your thoughts? There may well be a better way to approach this that I'm missing.

BTW I saw your Ember.js NYC video yesterday and it completely sold me on Ember Storefront, when I wasn't sure after reading though the docs. I suggest including the video in the docs!

**Comment by kalda341** [comment]
Also sorry for my super vague issue, looking back on it I can see that there was no way you were ever going to understand what I was on about!

**Comment by ryanto** [comment]
Thanks! The way we handle this in our applications is with nested includes. Since you’re using JSON:API you can use `reloadWith` like so:

```js
post.reloadWith(‘comments.votes’)
```

And that will get you all of the data you need.

You can also use `store.loadAll`, it’s like query, but it tries to be cache aware.

```js
await this.store.loadAll('comments', { filter: { post: this.post.id }, include: 'votes });
```

You said you were worried about nested includes, so if you still want to loop over each comment and fetch the votes you can use the `hasLoaded` API.

```js
post.comments.forEach(comment => {
  if (!comment.hasLoaded(‘votes’)) {
    // fetch comment’s vote here
  }
});
```

There's a potential problem with this for most backends though. This code will generate multiple requests, so it’s probably less efficient than using a nested include.

Also, unfortunately `hasLoaded` isn’t perfect and it may say a relationship has not been loaded when it already has. This is due to a limitation of Ember Data’s public APIs, so we err on the side of caution here and only return true when we’re 100% sure the data is loaded.

I know that none of the solutions are exactly what you were looking for, but I’d recommend giving them a shot. In JSON:API, nested includes are the recommended approach to solving this sort of problem, so I’d start there.

Let me know what you think.

**Comment by kalda341** [comment]
Nice! These are all great solutions.
I'll give them a go (when I get a chance, I worked around the original
problem.) If I find time I might submit a PR to your docs for these
suggestions.

Cheers!
