### ISSUE TITLE
Provide a helper function to see if loadAll was already called

### ISSUE THREAD

**Issue by Windvis** [embermap/ember-data-storefront#62]
It would be nice if there was a method which can be used to check if loadAll was already used. Something like `store.isLoaded('modelName');` maybe? This could be used to prevent unnecessary requests.

Let me explain with an example:
We have a route which loads all records with loadAll in the afterModel hook. Inside the template we have a component which does the same. (It's a standalone component which can be used on other pages which don't _need_ that data to function.) Because of this, the request gets fired twice.

Ideally it only happens once. With a helper like this, we could check the loaded state inside the dedicated component, before using loadAll.

Of course, it could also mean that our architecture is just bad, and we need to restructure 😁.

Thoughts?

**Comment by samselikoff** [comment]
We actually do provide a [`hasLoaded` helper](https://embermap.github.io/ember-data-storefront/docs/api/mixins/loadable-model#hasLoaded) for Models to check on the status of their relationships; I think providing a `store.hasLoaded(query)` helper lines us nicely with that!

Regarding the architecture, we've encountered your exact problem in our own apps as well. Our vision for the "real" answer here is to make Storefront's cache configurable, so that you can configure how often it refreshes a query. We think data queries (either in model hooks or in components) should all be declarative ("In order to render, I need User:1 and their included posts") and the tooling can help decide whether to hit the server or not when a given query is encountered.

But for today, I think `store.hasLoaded(query)` is a great escape hatch.

I'm going to mark this as a feature request, and a PR would be welcome from you (or anyone) who has time to contribute!
